BEGIN TRANSACTION;
DROP TABLE IF EXISTS "user1";
CREATE TABLE IF NOT EXISTS "user1" (
	"UID"	TEXT NOT NULL UNIQUE,
	"Uright"	INTEGER NOT NULL,
	"Uname"	TEXT NOT NULL,
	"Upasswd"	TEXT NOT NULL,
	"Umail"	TEXT UNIQUE,
	"Uxuehao"	TEXT UNIQUE,
	PRIMARY KEY("UID")
);
INSERT INTO "user1" VALUES ('0001',7,'test0','test0',NULL,NULL);
INSERT INTO "user1" VALUES ('0002',7,'test2','test2',NULL,NULL);
INSERT INTO "user1" VALUES ('0003',7,'eusername','epassword',NULL,NULL);
COMMIT;
