BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "user1" (
	"UID"	TEXT NOT NULL UNIQUE,
	"Uright"	INTEGER NOT NULL,
	"Uname"	TEXT NOT NULL UNIQUE,
	"Upasswd"	TEXT NOT NULL CHECK(LENGTH("Upasswd") >= 6),
	"Umail"	TEXT UNIQUE,
	"Uxuehao"	TEXT UNIQUE,
	PRIMARY KEY("UID")
);
INSERT INTO "user1" VALUES ('0001',7,'test0','test000',NULL,NULL);
INSERT INTO "user1" VALUES ('0002',7,'test2','test222',NULL,NULL);
INSERT INTO "user1" VALUES ('0003',7,'eusername','epassword',NULL,NULL);
INSERT INTO "user1" VALUES ('0004',1,'123131dfdf','123123123','dfcecaecsef@qweqwe.cdc',NULL);
COMMIT;
